= Executive Summary
:doctype: book
:sectnums: 
:toc: left
:toc-title: Table of Contents
:xrefstyle: full
:chapter-signifier: E.S.
:figure-caption: Figure
:table-caption: Table
:pdf-theme: ..//..//mshcp-theme.yml
:stylesheet: ..//..//styles.css
:experimental:
:source-highlighter: highlight.js
:icons: font

[.lead]
The Coachella Valley Multiple Species Habitat Conservation Plan balances environmental protection and economic development objectives while simplifying compliance with endangered species laws.

[#_e_s_1]
== Background, Purpose, Scope, Process, and Regulatory Context
A Scoping Study prepared for the Coachella Valley Association of Governments (CVAG) by the Coachella Valley Mountains Conservancy (CVMC) in 1994 recommended that a Multiple Species Habitat Conservation Plan (Plan) be prepared for the entire Coachella Valley and surrounding mountains to address current and potential future state and federal Endangered Species Act issues in the Plan Area. (See Figures 1-1 and 1-2 in Section 1 for maps of the Plan Area and its regional context.) A Memorandum of Understanding ("Planning Agreement") was developed to govern the preparation of the Plan. In late 1995 and early 1996, under the auspices of CVAG, the cities of Cathedral City, Coachella, Desert Hot Springs, Indian Wells, Indio, La Quinta, Palm Desert, Palm Springs, and Rancho Mirage; County of Riverside (County); U.S. Fish and Wildlife Service (USFWS); California Department of Fish and Game (CDFG); Bureau of Land Management (BLM); U.S. Forest Service (USFS); and National Park Service (NPS) signed the Planning Agreement to initiate the planning effort. Subsequently, Caltrans, Coachella Valley Water District (CVWD), Imperial Irrigation District (IID), Riverside County Flood Control and Water Conservation District (County Flood Control), Riverside County Regional Park and Open Space District (County Parks), Riverside County Waste Resources Management District (County Waste), California Department of Parks and Recreation (State Parks), and CVMC decided to participate in the Plan.

In late 1996 and early 1997, the Parties to the Planning Agreement approved an amendment stipulating that the Plan will meet the intent of the Natural Community Conservation Planning Act (NCCP Act) as well as the California Endangered Species Act (CESA) and the Federal Endangered Species Act (FESA), and, further, that the Planning Agreement constitutes an agreement to prepare a Natural Community Conservation Plan (NCCP) as specified in California Fish and Game Code Section 2810.

The Plan and Final EIR/EIS were released in early 2006 for local jurisdiction approval. In June 2006, the City of Desert Hot Springs voted not to approve the Plan. The CVAG Executive Committee then rescinded its approval of the Plan and directed that the Plan be revised to remove Desert Hot Springs as a Permittee and reflect other project description modifications that had been suggested during public review. This recirculated Draft Plan implements that direction.

The Plan balances environmental protection and economic development objectives in the Plan Area and simplifies compliance with endangered species related laws. The Plan is intended to satisfy the legal requirements for the issuance of Permits that will allow the Take of species covered by the Plan in the course of otherwise lawful activities. The Plan will, to the maximum extent practicable, minimize and mitigate the impacts of the Taking and provide for Conservation of the Covered Species.

The Plan has been prepared under the direction of CVAG, which contracted with CVMC for Plan preparation. A Project Advisory Group (PAG), composed of representatives of the Parties to the Planning Agreement; other public agencies, including CVWD and the University of California (UC); and private sector groups, including the Building Industry Association, the Sierra Club, The Nature Conservancy (TNC), the Center for Natural Lands Management (CNLM), and the Riverside County Farm Bureau, has provided a forum for input from an array of interests. All PAG meetings have been public meetings to provide an opportunity for public input. Public forums were held in 1998, 1999, and 2000, and special meetings and contact by mail have provided opportunities for potentially affected landowners to offer input into the planning process.

A Scientific Advisory Committee (SAC) provided technical expertise on biological issues. The SAC is made up of biologists from BLM, NPS, USFS, UC, initially TNC and subsequently CNLM, and CVWD, and one non-biologist who provided liaison with the PAG. USFWS and CDFG (Wildlife Agencies) have also attended most SAC meetings. A Geographic Information Systems (GIS) Team, composed of staff from BLM, CVAG, CVMC, and the County, has provided GIS services, including developing data layers, natural communities and species distribution mapping and modeling, gap analysis, and reserve design and corridor mapping.

The proposed term of the Permits is 75 years, which is the length of time required to fully fund Plan implementation. The acquisition program is projected to require 30 years to acquire all the Permittee obligation land. Full funding of the endowment for the Monitoring Program, the Management Program, Adaptive Management, and ongoing administration costs is projected to require 75 years.

== Plan Area Profile

The Coachella Valley is a broad, low elevation, northwest-southeast trending valley comprising the westernmost limits of the Sonoran Desert. It is located in the eastern portion of Riverside County, approximately 100 miles east of Los Angeles. Riverside County as a whole covers over 4,700,000 acres (7,310 square miles), making it California's fourth largest county and roughly equal in size to Connecticut.

The Plan Area boundaries were chosen to maximize inclusion of the Coachella Valley watershed. Portions of the watershed outside Riverside County or outside the jurisdictional boundaries of CVAG were not included in order to avoid institutional and administrative complexity. The Plan Area extends westward to Cabazon where it is bounded by the range line common to Range 1 East and Range 2 East. This is approximately the limit of the Sonoran or Colorado Desert in the San Gorgonio Pass area. The easternmost extent of the Plan Area is the range line common to Range 13 East and Range 14 East. Either the ridgeline of the Little San Bernardino Mountains or the boundary line with San Bernardino County where the ridgeline extends north of the county line bounds the Plan Area on the north. On the south, either the ridgeline of the San Jacinto and Santa Rosa Mountains or the boundary line with San Diego and Imperial Counties forms the Plan Area boundary. The Plan Area encompasses approximately 1.2 million acres. Of this, approximately 69,000 acres are Indian Reservation Lands, which are not included in the Plan, leaving a total of approximately 1.1 million acres addressed by the Plan.

Based on census data, the average annual growth rate in the 1970s in the Plan Area was just over 4.1%. This rose to over 5.8% in the 1980s. The annual growth rate between 1990 and 2000 was approximately 3.4%. The rate is projected to decline thereafter to less than 3% per year according to the Southern California Association of Governments Regional Transportation Plan Growth Forecast. It should be noted, however, that the estimated increase in population remains significant after the year 2000, with nearly an anticipated 145,000 new people added between 2000 and 2020. That is more than the total population of the Plan Area in 1980.

The cities of Cathedral City, Coachella, Desert Hot Springs, Indian Wells, Indio, La Quinta, Palm Desert, Palm Springs, and Rancho Mirage lie within the Plan Area, principally on the floor of the Coachella Valley. Together their jurisdictions make up approximately 16% of the Plan Area. The remaining 84% of the Plan Area is unincorporated. Approximately 41% of the land covered by the Plan is privately held. Though not included in the Plan, Indian Reservations within the Plan Area include the Morongo, Agua Caliente, Santa Rosa, Cabazon, Twenty-Nine Palms, Torres-Martinez Band, and Augustine. The balance of the Plan Area is public land managed by various local, state, and federal agencies, including BLM, USFS, NPS, USFWS, Bureau of Reclamation (BOR), CDFG, State Parks, UC, CVMC, and special districts, and open space lands owned by the Cities of Cathedral City, Coachella, Desert Hot Springs (which is not a Permittee), Indian Wells, Indio, La Quinta, Palm Desert, Palm Springs, and Rancho Mirage and the County.

Data derived from the Plan database indicate that approximately 6.0% of the Plan Area is currently urbanized, 1.0% is in rural development, 7.5% of the land is under agriculture, 0.5% has wind energy development on it, and 28.0% is vacant land under private or public non-conservation ownership. Of the remaining land in the Plan Area, 4.0% is covered by the Salton Sea, and 53.0% is public or Private Conservation Land.

While public land and Private Conservation Lands in some areas constitute large blocks of Habitat, in other areas the Habitat on public lands is fragmented by the checkerboard pattern of public lands and Private Conservation Lands with non-conservation private lands. The Conservation lands are not distributed in such a way as to provide adequate protection for all types of Habitat, or to protect Essential Ecological Processes for some Habitats, and Biological Corridors and Linkages for wildlife movement between major open space areas.

== Plan Development

The conservation plan was developed in consultation with the SAC, using best available science. The SAC developed a methodology for use in assessing the relative biological value of lands within the Plan Area and the subsequent development of a Preferred Alternative conservation plan. The Peninsular bighorn sheep conservation strategy was primarily based on the _Recovery Plan for Bighorn Sheep in the Peninsular Ranges, California_ (USFWS 2000).

The Plan recognizes that there is inevitably an uncertainty factor in scientific information about biological systems. The Monitoring and Adaptive Management Program is designed to increase the level of knowledge about species covered by the Plan, conserved natural communities, ecological processes, and connectivity. Changes in management of the Conservation Areas, and minor boundary changes, could result from such increased knowledge. Any such changes would be consistent with the No Surprises Assurances Rule of USFWS and CDFG assurances.

The conservation planning process reflects the broadest goals of the Plan, which are:

* Represent native ecosystem types or natural communities across their natural range of variation in a system of conserved areas.

* Maintain or restore viable populations of the species included in the Plan so that Take Permits can be obtained for currently Listed animal species and Non-listed animal species can be covered in case they are listed in the future.

* Sustain ecological and evolutionary processes necessary to maintain the viability of the conserved natural communities and Habitats for the species included in the Plan.

* Manage the system adaptively to be responsive to short-term and long-term environmental change and to maintain the evolutionary potential of lineages.

The planning process consisted of the steps described below.

1. _Determine the species and natural communities to be included in the Plan._ The planning team developed the initial list of species and natural communities to be considered. The list was narrowed down through the planning process as described in Section 3.2.

2. _Gather information on the species and natural communities_. Information was gathered on individual species from the following sources: (1) existing information from the literature, including Environmental Impact Reports (EIRs) and other environmental documents, museum records, and other reports on species distribution and ecological requirements; (2) California Natural Diversity Data Base (CNDDB) records; (3) presence/absence surveys for species about which more information was needed in selected areas where they have a probability of occurring and some potential to be protected; and (4) information and location maps provided by individual biologists. Information on the natural communities was gathered from: (1) the University of California at Santa Barbara Gap Map (2) LANDSAT satellite thematic mapping imagery, (3) color infrared aerial photographs, (4) blue-line aerial photographs of the Plan Area; (5) aerial photographs from 1939 and 1954 for historic natural communities, and (6) the CNDDB and the Palm Springs Desert Museum for desert fan palm oases.

3. _Prepare accounts of individual species and natural communities_. These accounts summarize available information on species' life history, habitat and ecological requirements, overall range, distribution within the Plan Area, threats, and conservation needs. Similar accounts were prepared on the composition and distribution of natural communities, threats, and conservation needs.

4. _Gather other pertinent information_. Information was also gathered and entered into the GIS database regarding existing conservation lands, topography and other natural features, watersheds, ecological processes, roads, and current land uses. Information on projected land uses, parcel configuration, and political boundaries was also gathered for use in developing implementation measures.

5. _Prepare a Natural Communities Map._ A Natural Communities Map was prepared to delineate the distribution of the natural communities in the Plan Area. This information was used in (1) modeling species' habitat distribution, (2) developing the Site Identification Maps, and (3) evaluating whether adequate protection will be afforded to the conserved natural communities on which the Plan focuses pursuant to the NCCP Act.

6. _Analyze biological resource information to map species' distribution_. Species' Habitat distribution maps were prepared for all species except burrowing owl using known occurrences, Habitat associations based on the Natural Communities Map, and, where relevant, elevation ranges of the species, landform data, sand source data, and soils data. Consensus was then obtained as to the adequacy and accuracy of information about the distribution of species in the Plan Area. Models were prepared for species for which sufficient data existed to use in developing a model. For the burrowing owl only known location information was used in conservation planning.

7. _Develop Site Identification Maps_. Site Identification Maps were developed by mapping at the quarter-section level and analyzing data regarding species richness, natural community richness, habitat heterogeneity, and habitat fragmentation, and refining the resulting maps using information about Essential Ecological Processes necessary to sustain Habitats, Core Habitat, endemic species occurrences, and other pertinent information. The Site Identification Maps delineate the areas of highest biological resource value in the Plan Area. See Appendix I for a detailed description of the Site Identification process.

8. _Delineate Core Habitat areas, Essential Ecological Process areas, and Biological Corridors and Linkages._ For each of the species for which sufficient data were available, Core Habitat areas were delineated, defined as areas of unfragmented Habitat with intact Essential Ecological Processes large enough to sustain a viable population of the species. See Appendix I for additional information on this process. Areas needed to maintain Essential Ecological Processes to sustain Core Habitat, and Biological Corridors and Linkages were also identified.

9. _Develop Conservation alternatives._ Three Conservation alternatives were initially developed for consideration. Conservation Alternative 1 consisted of existing public lands and Private Conservation Lands only. This alternative was included to assess the extent to which Existing Conservation Lands would suffice to protect the Covered Species and the conserved natural communities included in the Plan. Based on the Site Identification Maps, Conservation Alternative 2 was developed to provide Core Habitat for the Covered Species, protect Essential Ecological Processes to sustain those Habitat areas, provide Biological Corridors among Conservation Areas, and conserve natural communities as functioning ecosystems. The Biological Corridors were intended to provide not only for movement of Covered Species, but also for other species, including coyotes, bobcats, mountain lions, and foxes, necessary to maintain predator-prey relationships, general biological diversity, and the opportunity for species adaptation in response to potential climate change. Conservation Alternative 3 included additional areas with potential Conservation value as Habitat, corridor, and ecological process areas. A statistical analysis of the Conservation alternatives was prepared to provide information about the acreage of Habitat protected for each species and natural community under each alternative. The statistical analysis provided quantitative information on species and natural community protection, which was useful in conjunction with the qualitative analysis conducted in Step 10 using the conservation criteria.

10. _Develop and use criteria for evaluating the conservation alternatives._ Criteria were created to evaluate whether or not the Conservation Areas provide adequate protection for the species and natural communities on which the Plan focuses.

11. _Conduct Independent Science Advisors (ISA) Review._ During the course of the planning process, two workshops were held with leading conservation biologists Dr. Reed Noss, Dr. Michael Soulé, and Dr. C. Richard Tracy to get their input on the conservation plan. The ISA included the aforementioned conservation biologists as well as other scientists. (See Appendix I for additional information.) In early 2001, the ISA reviewed the work completed to date. In addition, a preliminary draft of a study titled _Long-term Sand Supply to Coachella Valley Fringe-toed Lizard (Uma inornata) Habitat in the Northern Coachella Valley, California_ (United States Geological Survey 2000) was made available.

12. _Develop a Preferred Alternative._ The Conservation Area maps prepared by CVAG were discussed in a series of meetings among CDFG, USFWS, CVAG staff, and local jurisdictions to evaluate land use, and economic and biological considerations. Through this process, the proposed Conservation Areas were further refined and a preferred alternative was developed

13. _Delineate Conservation Goals and Objectives._ Conservation Goals and specific Conservation Objectives were developed for each Covered Species, natural community, Essential Ecological Process, Biological Corridor, and Linkage in the Conservation Areas to ensure that Conservation would be accomplished and that the tools for compliance monitoring were in place.

[discrete]
=== Covered Species and Conserved Natural Communities

The Planning Agreement identified 52 species to be considered for inclusion in the Plan and targeted all the natural communities in the Plan Area. As information was gathered through the planning process, the Planning Team continuously reviewed the list. Other experts on individual species were also consulted. The 27 species ultimately included in the Plan are listed in Table 3-1 in Section 3 of the Plan. There are five plants, two insects, one fish, one amphibian, three reptiles, eleven birds, and four mammals.

The Planning Agreement listed 23 natural communities known to occur in the Plan Area. Through the planning process a total of 46 natural communities were identified in the Plan Area. Of these, 27 natural communities provide Habitat for the Covered Species and are the focal point for establishment of Conservation Areas. The natural communities included in the Plan's Conservation Areas are listed in Table 3-3 in Section 3 of the Plan. The other natural communities are not included in the Conservation Areas established under this Plan; however, with three exceptions, these other natural communities are already adequately protected in the Plan Area on public lands. The three exceptions that are not either currently protected or proposed for protection under this Plan are active shielded desert dunes, Riversidean desert scrub, and tamarisk scrub. Only a fragment of the active shielded desert dunes, surrounded by urbanization and shielded from Essential Ecological Processes, occurs in the Plan Area. Riversidean desert scrub is restricted to the San Gorgonio Pass in the Plan Area, where it occurs primarily on the Morongo Indian Reservation, which is not part of the Plan. It is more common in the western part of the County, where it is addressed in the Western Riverside County Multiple Species Habitat Conservation Plan (MSHCP). Tamarisk scrub is not a "natural" community in that it is dominated by an exotic plant species, i.e. tamarisk. In areas where some tamarisk scrub is included in the Conservation Areas, the intent is to restore it to the appropriate natural community to the maximum extent practicable.

[#_e_s_4]

== Establishment of the MSHCP Reserve System
The Conservation Plan includes the establishment of an MSHCP Reserve System, setting Conservation Objectives to ensure the Conservation of the Covered Species and conserved natural communities in the MSHCP Reserve System, provisions for management of the MSHCP Reserve System, and a Monitoring Program, and Adaptive Management. The MSHCP Reserve System will be established from lands within 21 Conservation Areas. Because some Take Authorization is provided under the Plan for Development in Conservation Areas, the actual MSHCP Reserve System will be somewhat smaller than the total acres in the Conservation Areas. When assembled, the Reserve System will provide for the Conservation of the Covered Species in the Plan Area.
For each Conservation Area, Conservation Objectives are articulated for conserving Core Habitat for Covered Species, Essential Ecological Processes necessary to maintain Habitat viability, Biological Corridors and Linkages as needed, and the less common conserved natural communities. Core Habitat has not been delineated for all species. Where it has not been delineated, Conservation Objectives are stated for either acres of Habitat or known occurrences.
The MSHCP Reserve System will be established within 21 Conservation Areas from the following components:

Existing Conservation Lands, managed by local, state, or federal agencies, or non-profit conservation organizations
Complementary Conservation
Additional Conservation Lands

The MSHCP Reserve System will be assembled as shown below:
[%header,cols="3,3,6"]
|===
|1996 |2006 |Lands
|458,800 |484,600 |Existing federal lands in MSHCP Reserve System^1^
|32,700 |44,600 |Existing state lands in MSHCP Reserve System
|900 |19,100 |Existing non-profit organization lands in MSHCP Reserve System^2^
|4,000 |8,800 |Existing Local Permittee Conservation lands in the MSHCP Reserve System
|496,400 |557,100 |SUBTOTAL
|69,290 |29,990 |Acres of Complementary Conservation
|39,850 |21,390 |Acres to be acquired by state and federal agencies
|7,500 |7,500 |Additional Local Permittee acres for which there will be cooperation to conserve
|93,100 |88,900 |Acres to be acquired or otherwise conserved by the Local Permittees
|10,800 |10,800 |Non-Permittee public and quasi-public lands
|7,800 |7,800 |Fluvial sand transport area where the Conservation Objective is met through non-acquisition. Development consistent with Conservation Objectives is allowed.^3^
|228,340 |166,380 |SUBTOTAL - COMPLEMENTARY CONSERVATION AND ADDITIONAL CONSERVATION LANDS
|22,660 |22,420 |Potential Development within Conservation Areas from Table 5-1.
|747,400 |745,900 |TOTAL -- CONSERVATION AREAS
|===
^1^ The acreage includes lands purchased by non-profit organizations and donated to federal agencies.
^2^ The acreage includes lands owned by non-profit organizations but acquired with State grant funds or local funds.
^3^ These acres are in the Cabazon, Long Canyon, and West Deception Canyon Conservation Areas.
Implementation of the Plan must ensure that the Conservation Objectives delineated for each Conservation Area are achieved. Implementation relies on cooperation among all the signatories to the IA, including local, state, and federal agencies. Assembly of the MSHCP Reserve System is a necessary component of Plan implementation.

=== Existing Conservation Lands within Conservation Areas

The Conservation Areas contained approximately 496,400 acres of Existing Conservation Lands as of 1996. By November 2006, this had increased to approximately 557,100 acres. These are lands in public or private ownership that are managed for Conservation and/or open space values, and which contribute to the Conservation of the Covered Species and the conserved natural communities included in the Plan. Federal lands within the MSHCP Reserve System that will contribute to the Conservation of the Covered Species include lands administered by the BLM, BOR, NPS, USFWS, and USFS. State lands within the MSHCP Reserve System that will contribute to the Conservation of the Covered Species include lands administered by the CDFG, State Parks, CVMC, and UC. The federal and state Existing Conservation Lands are summarized in Table 4-2 in Section 4.1. The Local Permittees will cooperate to conserve identified Local Permittee-owned land in perpetuity in the MSHCP Reserve System. The existing Local Permittee and CVFTL HCP Mitigation Lands and their status are summarized in Table 4-3 in Section 4.1. Various non-profit conservation organizations own land in the MSHCP Reserve System, which they acquired for conservation purposes. CVCC will seek agreements with these non-profit organizations to ensure the permanent Conservation and management of these lands pursuant to the Plan, including providing access to the property for biological monitoring and management purposes. Non-profit conservation organization Existing Conservation Lands are shown in Table 4-4 in Section 4.1.
The Existing Conservation Lands include the CVFTL Preserve system established pursuant to the CVFTL HCP, approved in 1986. Three preserves were established: Coachella Valley (Thousand Palms), Whitewater River Floodplain, and Willow Hole-Edom Hill. As described in Section 16.2 of the IA, it is the Parties' intent that the lands acquired under the CVFTL HCP will be subsumed into and managed as part of the MSHCP Reserve System. The Coachella Valley fringe-toed lizard is a Covered Species under the MSHCP.

=== Complementary Conservation

Several acquisition efforts for conservation purposes pre-date the MSHCP, and are ongoing efforts expected to conserve approximately 29,990 acres in the MSHCP Reserve System from November 2006 on. These include BLM and USFS acquisition programs in the Santa Rosa and San Jacinto Mountains National Monument, BLM Wilderness inholdings acquisitions, and inholdings acquisitions in Joshua Tree National Park. These acquisition programs pre-date the MSHCP, have broader rationales than the MSHCP program, and are independent of the MSHCP effort. They complement implementation of the MSHCP, but are not a Permittee obligation for purposes of the authorization of Take.

=== Additional Conservation Lands

A minimum of 129,690 acres in the Conservation Areas will be conserved as Additional Conservation Lands, to be acquired or otherwise conserved through state and federal acquisitions and Permittee contributions. The Local Permittees will also protect the fluvial sand transport Essential Ecological Process on approximately 7,800 acres in the Cabazon, Long Canyon, and West Deception Canyon Conservation Areas through application of general plan land use designations and policies, and flood control guidelines.
Through the MSHCP and its IA, the federal and state governments have agreed to partner with the Local Permittees in assembling, managing, and monitoring Reserve Lands. The federal and state governments will acquire approximately 21,390 acres of privately owned lands (this federal and state obligation is beyond any mitigation obligations for Development authorized by Local Permittees pursuant to the Plan) in the Conservation Areas after November 2006, as well as manage certain federal and state Existing Conservation Lands in the MSHCP Reserve System, and participate in the Monitoring and Adaptive Management Program for Reserve Lands. The Permittees (Local and State) have an obligation to conserve approximately 115,140 acres in the Conservation Areas through:

Conservation of 7,500 acres of currently non-conserved Local Permittee-owned lands. [See Section 4.2.2.2.1.]
Conservation of 88,900 acres of Additional Conservation Lands by the Local Permittees and Caltrans through acquisition or other means, such as planning tools and land use regulation, and acquisition of 640 acres by State Parks (after 1996), of which 100 acres can be developed for State Park facilities. [See Section 4.2.2.2.2.]
Management of 18,200 acres of Permittee Existing Conservation Lands consistent with the MSHCP. [See Section 4.2.2.2.3.]

In addition, the Permittees will maintain the fluvial sand transport Essential Ecological Process in the Cabazon, Long Canyon, and West Deception Canyon Conservation Areas as described in Section 4.2.2.2.4.
In addition to acquisition, land in the Conservation Areas may be conserved through dedication, deed restriction, or granting of a conservation easement in conjunction with Development approvals and conservation incentives. Habitat conserved through planning tools and land use regulation shall be protected, prior to issuance of a grading permit, by fee title transfer, granting a conservation easement to CVCC or other approved entity, or recordation of a deed restriction. Rights of access for monitoring and management of the lands by CVCC, the Wildlife Agencies, or their designees shall be provided.

=== Conservation Areas

The Plan will result in the establishment of the MSHCP Reserve System, assembled from lands within 21 Conservation Areas, which, combined with the Monitoring Program and the Management Program, are designed to achieve the following Conservation Goals:

Represent native ecosystem types or natural communities across their natural range of variation in a system of conserved areas.
Maintain or restore self-sustaining populations or metapopulations of the species included in the Plan to ensure permanent Conservation so that Incidental Take Permits can be obtained for currently Listed animal species and Non-listed animal species can be covered in case they are listed in the future.
Sustain ecological and evolutionary processes necessary to maintain the functionality of the natural communities and Habitats for the species included in the Plan.
Maximize connectivity among populations and avoid habitat fragmentation within Conservation Areas to conserve biological diversity, ecological balance, and connected populations of Covered Species.
Minimize adverse impacts from off road vehicle use, illegal dumping, edge effects, exotic species, and other disturbances in accordance with the Management and Monitoring Programs.
Manage the Conservation Areas adaptively to be responsive to short-term and long-term environmental change and new science.

=== Required Avoidance, Minimization, and Mitigation Measures

The Plan includes certain requirements for Covered Activities in the Conservation Areas to avoid, minimize, and mitigate impacts to bighorn sheep Habitat, Biological Corridors, burrowing owl, covered riparian bird species, crissal thrasher, desert tortoise, fluvial sand transport, Le Conte's thrasher, mesquite hummocks and mesquite bosque natural communities, triple-ribbed milkvetch, Palm Springs pocket mouse, and Little San Bernardino Mountains linanthus. These measures do not apply to single-family homes and any non-commercial accessory uses and structures including but not limited to second units on an existing legal lot. The measures have limited application to O&M activities. To assist Permittees with implementation of these measures, CVCC will maintain maps of modeled Habitat and a Natural Communities Map and provide them to each of the Permittees. CVCC will also maintain a list of Acceptable Biologists who may be used to conduct surveys for specified Covered Species. CVCC will also maintain a list of survey protocols approved by either or both CDFG and USFWS.

=== Land Use Adjacency Guidelines

The purpose of the Land Use Adjacency Guidelines is to avoid or minimize indirect effects from Development adjacent to or within the Conservation Areas. Such indirect effects are commonly referred to as edge effects, and may include noise, lighting, drainage, intrusion of people into the adjacent Conservation Area, and the introduction of non-native plants and non-native predators such as dogs and cats. Edge effects will also be addressed through reserve management activities such as fencing.

=== Anticipated Take and Habitat Loss

Anticipated Take for Covered Species for which Habitat distribution models have been developed is measured in terms of Habitat acres affected by the Covered Activities both outside and within the Conservation Areas. For purposes of this calculation, it is assumed that all non-federal lands outside the Conservation Areas may be subject to Take. This represents a worst-case scenario, and Take or Habitat loss at that level is not likely to occur within the 75-year term of the Take Permits. The acres of Take or Habitat loss were determined by overlaying Habitat maps with the Plan Area map, and calculating the Habitat areas outside the Conservation Areas. In addition, a small percentage of Take can occur within the Conservation Areas under the Plan. The amount of such Take or Habitat loss has been calculated for each species and natural community and is shown in the tables in Section 4.6.

[#_e_s_5]
== Costs of and Funding for Plan Implementation

[#_costs_for_plan_implementation]
=== Costs for Plan Implementation

Plan implementation costs include the direct and indirect costs associated with land acquisition, the Monitoring Program, and the Management Program. Additional costs include staff costs associated with Plan administration. Cost projections are intended to provide a realistic estimate of the costs for Plan implementation. This also assists the Wildlife Agencies in determining if the Plan meets Permit issuance criteria. The actual costs over time may turn out to be more or less than those projected in this Plan.

As shown in Table 5-1, Conservation through acquisition and other means that needed to occur as of November 2006 for Reserve System Assembly was 159,680 acres. As described in Section 4.2, 29,990 acres of this is projected to occur through Complementary Conservation, leaving a balance of 129,690 acres. Of this, 10,800 acres are public-quasi public lands belonging to non-Permittees. As explained in Section 4.2.2.3, the Plan does not provide Take Authorization for activities on these lands and assumes that this acreage will be conserved through other means, which are not an obligation of the Permittees. That leaves a balance of 118,890 acres, of which 21,390 acres will be conserved by state and federal agencies as their Plan implementation contribution (this federal and state obligation is beyond any mitigation obligations for Development authorized by Local Permittees pursuant to the Plan). This includes 640 acres of acquisition by State Parks, of which 100 acres can be developed for State Park facilities, as one of its mitigation obligations as a Permittee. In addition to State Parks' acquisition, the Permittees will conserve an additional 97,500 acres through acquisition or other means. Of this, 7,500 acres are already owned by Permittees and that acreage will be conserved through the Plan. Thus the Permittees will acquire or otherwise conserve 90,000 acres as of November 2006. For purposes of estimating the maximum Plan implementation costs, it is assumed that all the approximately 90,000 acres to be conserved by the Local Permittees will be purchased. The actual acreage acquired by the Local Permittees could be less if some land is conserved through conditions of approval on Development or other means.

The projected Permittees' costs for Plan implementation are shown in the following tables:

[.center]
.Summary of Permittees' Expenditures and Balances over the 75-Year Term of the Permits
[cols="3,1,6", options="header"]
|===
|Amount |Item
|$115,414,000 |Non-acquisition program administration costs (from Table 5-3b)
|$254,294,000 |Monitoring Program (from Table 5-3b)
|$221,252,000 |Management Program (from Table 5-3b)
|$14,903,000 |Adaptive Management (from Table 5-3b)
|$526,705,000 |Land acquisition costs (from Table 5-3c l)
|$9,080,000 |Land improvement costs (from Table 5-3c)
|$24,565,000 |Acquisition program administrative costs (from Table 5-3c)
|$5,000,000 |Management Contingency Fund (from Table 5-3b)
|*$1,171,213,000* |*TOTAL Expenditures*
|$860,741,000 |Endowment Fund balance in Year 75 (from Table 5-3d)
|$5,386,000 |Fund balance in Operating Fund in Year 75 (from Table 5-3b)
|$1,200,000 |Repayment of Conservation Trust Fund advance to complete Plan
|*$2,038,540,000* |*TOTAL*
|===

In addition to the Permittees' monitoring and management responsibilities described in the preceding sections, CVWD has additional responsibilities, the costs of which are not included in the cost and revenue projections presented in Section 5. CVWD is required to fund the costs of the following:

- Establishing and providing a permanent water source for permanent Habitat for the California black rail and Yuma clapper rail in the Coachella Valley Stormwater Channel and Delta Conservation Area. See Section 4.3.20.

- Establishing and providing a permanent water source, as needed, for riparian Habitat for Covered riparian bird Species in the Coachella Valley Stormwater Channel and Delta Conservation Area. See Section 4.3.20.

- Establishing and providing a permanent water source for desert pupfish Habitat, and developing and implementing a monitoring and adaptive management program for desert pupfish in the agricultural drains and flood control channels. See Section 4.3.20.

- Restoring and enhancing mesquite and Coachella Valley round-tailed ground squirrel Habitat on CVWD land in the East Indio Hills Conservation Area if a study undertaken by the CVCC demonstrates the feasibility of mesquite restoration, and providing water, as needed, for maintaining the mesquite once established. See Section 4.3.15.

[#_funding_for_plan_implementation]
=== Funding for Plan Implementation

To accomplish the acquisition program in 30 years and fund the Monitoring Program and the Management Program endowment in 75 years, the Permittees will use a combination of annual revenues and debt financing in the form of the issuance of revenue bonds. This would provide the necessary funding for acquisition and establishment of the endowment in advance of the collection of all the revenue needed for those purposes.

The Permittees and the Wildlife Agencies will annually evaluate the performance of the funding mechanisms and, notwithstanding other provisions of the Plan, will develop any necessary modifications to the funding mechanisms to address additional funding needs. If deficiencies are identified through this evaluation, then the Permittees and the Wildlife Agencies will develop strategies to address any additional funding needs consistent with the terms and conditions of the Plan. The funding plan is intended to keep the rate of Conservation of Permittee Additional Conservation Lands roughly proportional with the amount of Development occurring in the Plan Area.

[.center]
.Summary of Revenue Sources
[cols="3,1,6", options="header"]
|===
|Amount |Revenue Source
|$516,802,000 |Local Development Mitigation Fee (from Table 5-3c)
|$227,604,000 |Conservation Trust Fund (from Table 5-3b)
|$31,077,000 |Regional Road Projects Mitigation (Measure A Sales Tax total contribution to acquisition and endowment; and freeway interchange/associated arterials contribution to endowment)
|$60,208,000 |Regional Infrastructure Mitigation (Caltrans, CVWD, and IID contributions to acquisition and endowment)
|$247,500,000 |Eagle Mountain Environmental Mitigation Trust Fund (from Table 5-3b)
|$3,200,000 |Transfer from CVFTL HCP Endowment
|$952,149,000 |Interest on Investments (from Tables 5-3b, 5-3c, and 5-3d; interest generated on money in the Operating Fund, the Land Acquisition and Improvement Fund, and the Endowment Fund)
|*$2,038,540,000* |*TOTAL Revenues*
|===

If at the end of any five (5) year period the "rough proportionality" test has not been met, the Local Permittees and the Wildlife Agencies will meet within ninety (90) days to begin to develop a strategy to address the need for a balance between Conservation and Development.

Maintaining the Permits does not depend on the state and federal governments' adhering to any specific schedule for land acquisition, nor on any specific appropriations to state and federal agencies for land management. State and federal agencies, including BLM, USFS, NPS, USFWS, Wildlife Conservation Board (WCB), CDFG, and CVMC, may receive funds from a variety of sources to implement their obligations under the Plan. Potential state and federal funding sources include, but are not limited to:

- State appropriations
- Federal Land and Water Conservation Fund
- Land exchange
- State Bond Acts
- FESA Section 6 funds.